name: Publish to GitHub pages

on:
    push:
        branches:
            - main

jobs:
    publish-pages:
        environment:
            name: main
            url: https://williamdes.eu
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY_DEPLOY }}
            - name: Import GPG key
              # v5.2.0 - 111c56156bcc6918c056dbef52164cfa583dc549
              uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Build and push
              run: |
                  set -o xtrace
                  make build
                  TEMP_DIR="$(mktemp -d --suffix=_website_williamdes)"
                  cp -rp williamdes.eu/public "${TEMP_DIR}"
                  git checkout gh-pages
                  git ls-files | xargs -r -n 1 rm
                  rm -rfd ./*
                  mv "${TEMP_DIR}"/public/* ./
                  rm -rf "${TEMP_DIR}"
                  echo 'williamdes.eu' > CNAME
                  git add -A
                  git commit --allow-empty -m "Content update ($(date --utc))"
                  git push
